### ISSUE TITLE
Separate inlining from mailing and testing

### ISSUE THREAD

**Issue by kyotoprotokollet** [Email-builder/gulp-email-builder#5]
Hi, 

Is there a way to separate the inlining-process from mailing and testing?
I would like to have a task with only inlining and some other task for mailing and testing, since I do not want to mail myself and run Litmus test each time I just want to inline some CSS.

**Comment by jeremypeter** [comment]
Hey @kyotoprotokollet is there a reason why wouldn't you want your css inlined?

**Comment by kyotoprotokollet** [comment]
Hi, you misunderstand me :) I do want inlining, I just want that process to be separate from mailing and testing. When I develop an email, I will make constant tweaks to code and CSS, so I will want to inline often, but I do not want to send a test to Litmus and an email to myself each time I just inline some CSS.

I know I can just comment out the emailTest and litmus Objects in options, but it would be much more smooth if I could run one gulp command for inlining and another for testing my email, for example!

**Comment by jeremypeter** [comment]
I would just create separate tasks

``` javascript
// Send to Litmus 
gulp.task('sendLitmus', function(){
  return gulp.src(['./example/html/email.html'])
    .pipe(emailBuilder({
      litmus : {...}
    }));
});

// Send to Email 
gulp.task('sendEmail', function(){
  return gulp.src(['./example/html/email.html'])
    .pipe(emailBuilder({
      emailTest: {...}
    }));
});
```

Then you just can run:

```
gulp sendLitmus
```

```
gulp sendEmail
```
