### ISSUE TITLE
emailTest call hangs once it's finished 

### ISSUE THREAD

**Issue by notasausage** [Email-builder/gulp-email-builder#6]
I'm using `gulp-email-builder` for sending test emails and Litmus tests of HTML emails and I've noticed that the `emailTest` call seems to work fine, but it doesn't properly exit once it's finished. I'll see the `Starting 'send'...` message on the console, the email will send, and then the `Finished 'send'` message on the console appears, but doesn't return me to a prompt. Eventually it will exit (60 seconds or so later), but I'm not sure why this happens.

Here's how I'm using it in my `gulpfile.js`:

``` javascript
gulp.task( 'send', ['deploy'], function() {
    return gulp.src( ['app/*.html'] )
        .pipe( replaceImages() )
        .pipe( emailBuilder( email_builder_send ) )
});
```

Where `replaceImages()` is a [lazypipe](https://github.com/OverZealous/lazypipe) and my `email_builder_send` options look like this:

``` javascript
email_builder_send = {
    encodeSpecialChars: true,

    emailTest: {
        email: test_emails,
        subject: email_subject,
        transport: {
            type: 'SMTP',
            options: {
                service: smtp_service,
                auth: {
                    user: smtp_username,
                    pass: smtp_password
                }
            }
        }
    }
}
```

There are variables being used for each option of course. I've tried several things, including not using `lazypipe`, and the task always hangs. I'm also using `gulp-email-builder` for sending Litmus tests and that task finishes without issue.

**Comment by jeremypeter** [comment]
Try using new version `v2.0.0`. The options for `emailTest` have [changed](https://github.com/Email-builder/email-builder-core#options)

Example: 

``` javascript
emailTest: {
  email : process.env.GMAIL_USER,
  subject : 'Email Subject',
  nodemailer: {
    transporter: {
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS
      }
    }
  }
}
```
